export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED";
export const NEW_MESSAGE_SENT = "NEW_MESSAGE_SENT";
export const SET_PREVIOUS_CONVERSATIONS = "SET_PREVIOUS_CONVERSATIONS";
export const CREATE_NEW_CONVERSATION = "CREATE_NEW_CONVERSATION";
